[formatter.nix]
command = "nixfmt"
includes = [ "*.nix" ]

[formatter.oxfmt]
command = "oxfmt"
options = [ "--write" ]
includes = [ "*.json", "*.yaml", "*.yml" ]

[formatter.shfmt]
command = "shfmt"
options = [ "-w" ]
includes = [ "*.sh" ]

[formatter.powershell]
command = "pwsh"
options = [
  "-NoProfile",
  "-Command",
  "& { $ErrorActionPreference = 'Stop'; if (-not (Get-Module -ListAvailable PSScriptAnalyzer | Where-Object Version -eq '1.22.0')) { Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.22.0 -Scope CurrentUser -Force -Repository PSGallery | Out-Null }; Import-Module PSScriptAnalyzer -RequiredVersion 1.22.0 -Force; $content = Get-Content -Raw -LiteralPath $env:FILENAME; $formatted = Invoke-Formatter -ScriptDefinition $content; Set-Content -LiteralPath $env:FILENAME -Value $formatted -Encoding utf8 }",
]
includes = [ "*.ps1" ]

[formatter.taplo]
command = "taplo"
options = [ "format" ]
includes = [ "*.toml" ]

[formatter.stylua]
command = "stylua"
includes = [ "*.lua" ]

# [formatter.dprint]
# command = "dprint"
# options = [ "fmt", "--allow-no-files" ]
# includes = [ "*.md" ]
