{ pkgs, lib, config, ... }:
let
  terminalsCfg = config.myHomeSettings.terminals;

  # Import shared keybindings
  sharedKeybindings = import ../keybindings.nix { leader = terminalsCfg.leader; };

  # Windows Terminal settings as Nix expression
  settings = {
    "$help" = "https://aka.ms/terminal-documentation";
    "$schema" = "https://aka.ms/terminal-profiles-schema";

    # Actions (from shared keybindings)
    actions = sharedKeybindings.windowsTerminal.actions;

    # Copy settings
    copyFormatting = "none";
    copyOnSelect = false;

    # Default profile (PowerShell Core)
    defaultProfile = "{574e775e-4f2a-5b96-ac1e-a2962a402336}";

    # Global settings
    language = "ja";
    alwaysShowNotificationIcon = true;
    useAcrylicInTabRow = true;
    showTabsFullscreen = true;

    # Keybindings (from shared keybindings)
    keybindings = sharedKeybindings.windowsTerminal.keybindings;

    # New tab menu
    newTabMenu = [{ type = "remainingProfiles"; }];

    # Profiles
    profiles = {
      # Default settings for all profiles
      defaults = {
        font = {
          face = "Consolas";
          size = 12;
        };
        useAcrylic = true;
        opacity = 85;
        colorScheme = "One Half Dark";
        cursorShape = "bar";
        padding = "8, 8, 8, 8";
      };
      list = [
        {
          commandline = "%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe";
          guid = "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}";
          hidden = false;
          name = "Windows PowerShell";
        }
        {
          elevate = true;
          guid = "{574e775e-4f2a-5b96-ac1e-a2962a402336}";
          hidden = false;
          name = "PowerShell";
          source = "Windows.Terminal.PowershellCore";
          backgroundImage = "desktopWallpaper";
          backgroundImageOpacity = 0.25;
          backgroundImageStretchMode = "uniformToFill";
          colorScheme = "CGA";
          opacity = 25;
        }
        {
          guid = "{2ece5bfe-50ed-5f3a-ab87-5cd4baafed2b}";
          hidden = false;
          name = "Git Bash";
          source = "Git";
        }
        {
          guid = "{265f58cc-343d-58ab-af9f-53bd9c7e769f}";
          hidden = false;
          name = "NixOS";
          source = "Microsoft.WSL";
        }
      ];
    };

    schemes = [ ];
    themes = [ ];
  };

  # Generate JSON file
  settingsJson = pkgs.writeText "windows-terminal-settings.json"
    (builtins.toJSON settings);
in
{
  # Export the generated settings path for scripts to use
  home.file.".config/windows-terminal/settings.json".source = settingsJson;

  # Also create an activation script hint
  home.file.".config/windows-terminal/README.md".text = ''
    # Windows Terminal Settings

    This directory contains Windows Terminal settings generated by Nix.

    ## Keybindings

    Keybindings are consistent with WezTerm:

    ### Pane Operations (Ctrl+Alt)
    | Action | Key |
    |--------|-----|
    | Split horizontal | Ctrl+Alt+H |
    | Split vertical | Ctrl+Alt+V |
    | Close pane | Ctrl+Alt+X |
    | Pane zoom | Ctrl+Alt+W |

    ### Pane Navigation (Ctrl+Shift)
    | Action | Key |
    |--------|-----|
    | Move left | Ctrl+Shift+H |
    | Move down | Ctrl+Shift+J |
    | Move up | Ctrl+Shift+K |
    | Move right | Ctrl+Shift+L |

    ### Other
    | Action | Key |
    |--------|-----|
    | Fullscreen | F11 |

    Note: Windows Terminal doesn't support Leader key.
    WezTerm Leader key: ${terminalsCfg.leader.mods}+${terminalsCfg.leader.key}

    ## Apply Settings

    Run from Windows PowerShell:
    ```powershell
    .\scripts\powershell\update-windows-settings.ps1
    ```
  '';
}
