[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]

[agents.warp_agent.input]
nld_in_terminal_enabled = true

[agents.warp_agent.other]
cloud_agent_computer_use_enabled = true

[privacy]
telemetry_enabled = true
crash_reporting_enabled = true

[account]
is_settings_sync_enabled = false

[terminal.input]
honor_ps1 = true
input_box_type_setting = "classic"

[appearance]

[appearance.text]
font_name = "UDEV Gothic NF"
ai_font_name = "UDEV Gothic NF"
match_ai_font = false
notebook_font_size = 10.0
font_size = 10.0

[appearance.themes]
system_theme = false
theme_name = "Catppuccin Mocha"
