[editor]
line-number = "relative"
mouse = true
auto-save = true
completion-trigger-word = true
rulers = [ 88, 120 ]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = [ "mode", "spinner", "file-name", "file-modification-indicator" ]
center = [ "file-type" ]
right = [ "diagnostics", "selections", "position", "file-encoding", "file-line-ending" ]

[editor.file-picker]
hidden = false

[keys.normal]
"C-/" = "toggle_comments"
